### PR TITLE
Conftest compatibility tweaks

### PR DESCRIPTION
**Pull request by simonbaird**
See also https://github.com/redhat-appstudio/build-definitions/pull/105 which should be merged at the same time.

### CODE REVIEW

**Comment by simonbaird** [comment]
Demo:
```
$ make clean-data clean-input fetch-att dummy-config check conftest-check
cosign download attestation "quay.io/lucarval/tekton-test@sha256:3dde9d48a4ba03187d7a7f5768672fd1bc0eda754afaf982f0768983bb95a06f" | \
  jq -s '{ "attestations": [.[].payload | @base64d | fromjson] }' > /home/sbaird/code/ec-policies/input/input.json
[]
[
        {
                "filename": "/home/sbaird/code/ec-policies/input/input.json",
                "namespace": "main",
                "successes": 1
        }
]
$ make clean-data clean-input fetch-att dummy-config
cosign download attestation "quay.io/lucarval/tekton-test@sha256:3dde9d48a4ba03187d7a7f5768672fd1bc0eda754afaf982f0768983bb95a06f" | \
  jq -s '{ "attestations": [.[].payload | @base64d | fromjson] }' > /home/sbaird/code/ec-policies/input/input.json
$ make check
[]
$ make conftest-check
[
        {
                "filename": "/home/sbaird/code/ec-policies/input/input.json",
                "namespace": "main",
                "successes": 1
        }
]
$ vi input/input.json 
$ make check
[
  {
    "msg": "Step 0 has disallowed registry 'quay.io/buildaaargh' for attestation."
  }
]
$ make conftest-check
[
        {
                "filename": "/home/sbaird/code/ec-policies/input/input.json",
                "namespace": "main",
                "successes": 0,
                "failures": [
                        {
                                "msg": "Step 0 has disallowed registry 'quay.io/buildaaargh' for attestation."
                        }
                ]
        }
]
make: *** [Makefile:148: conftest-check] Error 1
```

**Review by zregvart — APPROVED** [review]
LGTM

**Comment by simonbaird** [comment]
We might want to merge #23 first , not sure.

**Comment by simonbaird** [comment]
FYI I started looking at the changes needed so that the test results could also be part of the input. It's doable, but complicated, since it would be harder to maintain opa compatibility and we'd need non-trivial rego changes.

So (after slack discussion) I suggested we remove the test result data changes from https://github.com/redhat-appstudio/build-definitions/pull/105 . The reasoning:
* Avoid more complicated changes incompatible with existing rego
* Avoid spending time on a problem that is likely to go away if we can in fuure access result data in the pipelinerun attestion

**Comment by simonbaird** [comment]
Updates:
* Should be just about ready to merge
* There's been some back and forth on non_blocking_checks and where it is... long story but it's now back where it was.

**Comment by simonbaird** [comment]
Not sure why it won't trigger the CI, but it's passing for me locally at least.

**Comment by simonbaird** [comment]
As per discussion on slack, let's merge.

**Pull request merged**
