### PR TITLE
Publish documentation to GitHub Pages

### PR DESCRIPTION
**Pull request by zregvart**
Builds the documentation using Antora and publishes the built artifact
to GitHub pages.

### CODE REVIEW

**Comment by zregvart** [comment]
Includes #88 for the `make ci` to pass.

**Comment by simonbaird** [comment]
Nice.

**Comment by simonbaird** [comment]
lgtm

**Review by simonbaird — APPROVED** [review]

**Review by lcarva — APPROVED** [review]

**Comment by lcarva** [comment]
Should we remove the `docs` directory and the Makefile targets for keeping it up to date?

**Comment by zregvart** [comment]
> Should we remove the `docs` directory and the Makefile targets for keeping it up to date?

I'll create a followup to cleanup the remnants of Jekyll, let's see this version published first.

**Pull request merged**
