### PR TITLE
Short clickable anchor links in docs

### PR DESCRIPTION
**Pull request by simonbaird**

### CODE REVIEW

**Comment by simonbaird** [comment]
Note that there are some extra anchor links added by Github but they're long and unpleasant. This adds some shorter ones using the rule short name.

**Comment by simonbaird** [comment]
Preview:
* https://simonbaird.github.io/ec-policies/
* https://github.com/simonbaird/ec-policies/blob/anchor-links/docs/index.adoc
* https://github.com/simonbaird/ec-policies/blob/anchor-links/docs/index.md

**Review by zregvart — APPROVED** [review]

**Comment by simonbaird** [comment]
Added one more commit to include some explanatory intro text for each section.

**Comment by simonbaird** [comment]
Good enough probably. ...early and often..

**Pull request merged**
