### PR TITLE
rewriting to use conftest

### PR DESCRIPTION
**Pull request by joejstuart**

### CODE REVIEW

**Comment by simonbaird** [comment]
I'm getting a `Not found` on the curl command to download conftest.

**Comment by simonbaird** [comment]
Will debug some more tomorrow.

**Comment by joejstuart** [comment]
> ~Looks like there's no .tar.gz file for amd64~
> 
> Actually I fixed it by moving this so it applies for Linux too:
> 
> ```
> +ifeq ($(CONFTEST_GOARCH),amd64)
> +    CONFTEST_GOARCH=x86_64
> +endif
> ```
> 
> Not sure if the arch difference matters, but seems to work so far.

I'm not sure either. For some reason I thought it was only a Mac thing. I moved the `ifeq`

**Comment by simonbaird** [comment]
Re the coverage support for conftest, I found this: https://github.com/open-policy-agent/conftest/issues/518 .

So maybe we need to keep opa binary around for the coverage check.

**Comment by simonbaird** [comment]
There's some pieces here that aren't in #30 so I think this PR is still good. Needs a rebase and some careful selection of hunks.

**Comment by simonbaird** [comment]
Or perhaps it's better to start fresh and add the `make fmt` and make `install-conftest` change in a new PR.

**Comment by lcarva** [comment]
Is this still relevant?

**Pull request closed without merging**
